Repository avasachinbaijal/AvaTax-REST-V3-PHP-SDK, pull requests merged in 2022-02, with the labels that each got.

#29 Update for 2.4.7.1
  README.md
  composer.json
  lib/API/AgeVerificationApi.php
  lib/API/ShippingVerificationApi.php
  lib/Model/AgeVerifyFailureCode.php
  lib/Model/AgeVerifyRequest.php
  lib/Model/AgeVerifyRequestAddress.php
  lib/Model/AgeVerifyResult.php
  lib/Model/ErrorDetails.php
  lib/Model/ErrorDetailsError.php
  lib/Model/ErrorDetailsErrorDetails.php
  lib/Model/ModelInterface.php
  lib/Model/ShippingVerifyResult.php
  lib/Model/ShippingVerifyResultLines.php
  phpunit.xml.dist
Labels: 2.4.7.1

#30 Update for 2.4.7.2
  README.md
  composer.json
  lib/API/AgeVerificationApi.php
  lib/API/ShippingVerificationApi.php
  lib/Model/AgeVerifyFailureCode.php
  lib/Model/AgeVerifyRequest.php
  lib/Model/AgeVerifyRequestAddress.php
  lib/Model/AgeVerifyResult.php
  lib/Model/ErrorDetails.php
  lib/Model/ErrorDetailsError.php
  lib/Model/ErrorDetailsErrorDetails.php
  lib/Model/ModelInterface.php
  lib/Model/ShippingVerifyResult.php
  lib/Model/ShippingVerifyResultLines.php
Labels: 2.4.7.2

#31 Update for 2.4.7.3
  README.md
  composer.json
  lib/API/AgeVerificationApi.php
  lib/API/ShippingVerificationApi.php
  lib/Model/AgeVerifyFailureCode.php
  lib/Model/AgeVerifyRequest.php
  lib/Model/AgeVerifyRequestAddress.php
  lib/Model/AgeVerifyResult.php
  lib/Model/ErrorDetails.php
  lib/Model/ErrorDetailsError.php
  lib/Model/ErrorDetailsErrorDetails.php
  lib/Model/ModelInterface.php
  lib/Model/ShippingVerifyResult.php
  lib/Model/ShippingVerifyResultLines.php
Labels: 2.4.7.3

#33 Update for 2.4.7.5
  README.md
  lib/API/AgeVerificationApi.php
  lib/API/ShippingVerificationApi.php
  lib/Model/AgeVerifyFailureCode.php
  lib/Model/AgeVerifyRequest.php
  lib/Model/AgeVerifyRequestAddress.php
  lib/Model/AgeVerifyResult.php
  lib/Model/ErrorDetails.php
  lib/Model/ErrorDetailsError.php
  lib/Model/ErrorDetailsErrorDetails.php
  lib/Model/ModelInterface.php
  lib/Model/ShippingVerifyResult.php
  lib/Model/ShippingVerifyResultLines.php
  phpunit.xml.dist
Labels: 2.4.7.5

#44 Update for 2.4.20
  README.md
  lib/API/AgeVerificationApi.php
  lib/API/ShippingVerificationApi.php
  lib/Model/AgeVerifyFailureCode.php
  lib/Model/AgeVerifyRequest.php
  lib/Model/AgeVerifyRequestAddress.php
  lib/Model/AgeVerifyResult.php
  lib/Model/ErrorDetails.php
  lib/Model/ErrorDetailsError.php
  lib/Model/ErrorDetailsErrorDetails.php
  lib/Model/ModelInterface.php
  lib/Model/ShippingVerifyResult.php
  lib/Model/ShippingVerifyResultLines.php
Labels: 2.4.20

#51 Update for 2.4.26
  README.md
  lib/API/AgeVerificationApi.php
  lib/API/ShippingVerificationApi.php
  lib/Model/AgeVerifyFailureCode.php
  lib/Model/AgeVerifyRequest.php
  lib/Model/AgeVerifyRequestAddress.php
  lib/Model/AgeVerifyResult.php
  lib/Model/ErrorDetails.php
  lib/Model/ErrorDetailsError.php
  lib/Model/ErrorDetailsErrorDetails.php
  lib/Model/ModelInterface.php
  lib/Model/ShippingVerifyResult.php
  lib/Model/ShippingVerifyResultLines.php
Labels: 2.4.26
